# Generated by Django 4.1 on 2022-08-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_account', '0004_alter_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
